In [120]:
import pandas as pd

# Gathering

In [121]:
df = pd.read_csv('sayur_buah_raw_v1.csv')

print(df.shape)
df.head()

(315, 9)


,item_name,item_type,freshness_score_visual,standard_shelf_life_fridge,standard_shelf_life_room,water_content_pct,ethylene_producer,respiration_rate,sensitivity_to_chilling
0,Stroberi,Berry,0.58,5.0,1.0,89.5,False,HIGH,False
1,Sawi Hijau,Leafy Vegetable,0.82,5.0,0.0,NaN,False,High,False
2,Lemon,NaN,0.86,20.0,6.0,89.4,False,Low,NaN
3,Pisang,Tropical Fruit,0.64,4.0,2.0,NaN,True,High,True
4,Sawi Hijau,Leafy Vegetable,0.81,5.0,1.0,91.2,False,High,NaN


## Assessing

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   item_name                   315 non-null    object 
 1   item_type                   291 non-null    object 
 2   freshness_score_visual      305 non-null    object 
 3   standard_shelf_life_fridge  310 non-null    float64
 4   standard_shelf_life_room    301 non-null    float64
 5   water_content_pct           286 non-null    object 
 6   ethylene_producer           293 non-null    object 
 7   respiration_rate            296 non-null    object 
 8   sensitivity_to_chilling     293 non-null    object 
dtypes: float64(2), object(7)
memory usage: 22.3+ KB


In [123]:
df.describe(include="all")

,item_name,item_type,freshness_score_visual,standard_shelf_life_fridge,standard_shelf_life_room,water_content_pct,ethylene_producer,respiration_rate,sensitivity_to_chilling
count,315,291,305,310.000000,301.000000,286,293,296,293
unique,43,35,48,NaN,NaN,155,11,15,12
top,Pepaya,Tropical Fruit,0.86,NaN,NaN,89.4,False,Low,False
freq,13,72,21,NaN,NaN,6,167,119,191
mean,NaN,NaN,NaN,17.987097,6.920266,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,22.362992,10.324419,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,-20.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,6.000000,2.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,10.000000,4.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,19.750000,6.000000,NaN,NaN,NaN,NaN


In [124]:
df.isnull().sum()

,0
item_name,0
item_type,24
freshness_score_visual,10
standard_shelf_life_fridge,5
standard_shelf_life_room,14
water_content_pct,29
ethylene_producer,22
respiration_rate,19
sensitivity_to_chilling,22


In [125]:
df.duplicated().sum()

np.int64(11)

In [126]:
df['ethylene_producer'].unique()

array(['False', 'True', nan, 'TRUE', 'true', '1', 'no', '0', 'false',
       'FALSE', 'Tidak', 'Ya'], dtype=object)

In [127]:
df['freshness_score_visual'].unique()

array(['0.58', '0.82', '0.86', '0.64', '0.81', '0.69', '0.73', '0.89',
       '0.74', '0.7', 'Segar', '0.65', '2.0', '0.91', '0.9', '99.0',
       '0.76', '0.87', '0.8', '0.72', '0.88', '0.61', '0.77', '0.78',
       '0.92', nan, '0.85', '0.71', '0.84', '0.94', '0.68', 'Layu', '0.6',
       '0.93', '0.83', '0.56', '0.63', '0.66', '0.67', '0.62', '0.55',
       '-0.5', '0.57', '0.95', '0.79', '0.75', '0.96', '0.59', '1.5'],
      dtype=object)

In [129]:
df['item_type'].unique()

array(['Berry', 'Leafy Vegetable', nan, 'Tropical Fruit',
       'Temperate Fruit', 'Root Veg', 'citrus', 'Root Vegetable',
       'Citric Fruit', 'Chili', 'LEAFY VEGETABLE', 'Sayur Daun', 'CITRIC',
       'Beri', 'Buah Tropis', 'temperate fruit', 'berrys',
       'leafy vegetable', 'TEMPERATE', 'BERRY', 'citric fruit',
       'Akar-akaran', 'CHILI', 'Buah Citrus', 'Citrus Fruit', 'ROOT VEG',
       'Chile', 'tropical fruit', 'Tropis', 'TROPICAL', 'Sayur Akar',
       'root vegetable', 'Buah Sedang', 'Temperate', 'Cabai', 'Berries'],
      dtype=object)

In [130]:
df['respiration_rate'].unique()

array(['HIGH', 'High', 'Low', 'high', 'Medium', nan, 'Rendah', 'low',
       'high ', 'Hi', 'Sedang', 'MEDIUM', 'L', 'Tinggi', 'LOW', 'Med'],
      dtype=object)

In [131]:
df['sensitivity_to_chilling'].unique()

array(['False', nan, 'True', 'true', '0', 'Tidak', 'FALSE', 'TRUE', 'no',
       'false', 'Ya', '1', 'yes'], dtype=object)

In [132]:
df['standard_shelf_life_fridge'].unique()

array([  5.,  20.,   4.,   6.,  92.,   7.,  19.,  29.,  87.,  15.,  13.,
        14.,  10.,  12.,  85.,  90.,  22.,  31.,   9.,  21.,   3.,  nan,
        98.,  57.,  18., -20.,  28.,  91.,   0.,  95.,  61.,  30.,  58.,
        83.,  94.,  84.,  65.,  60.,  97.,  27.,  23.,  86.,  96.,  62.,
        81.,  88.])

In [133]:
df['standard_shelf_life_room'].unique()

array([ 1.,  0.,  6.,  2.,  3., 44., 14., nan,  5.,  4., 26.,  7., 51.,
       12., 10., 48.,  8., 29., 27., 11., 40., 33., 32., 47., 28., 31.,
       15., 30.,  9.])

In [134]:
df['water_content_pct'].unique()

array(['89.5', nan, '89.4', '91.2', '88.0', '82.1', '63.5', '92.8',
       '90.2', '82.7', '88.9', '79.6', '92.1', '81.1', '90.7', '63.3',
       '86.4', '85.8', '90.6', '88.4', '81.4', '87.6', '80.0', '90.8',
       '90.4', '88.3', '71.5', '89.7', '84.8', '97.0', '85.7', '82.3',
       '84.1', '87.7', '91.5', '89.6', '92.7', '61.4', '88.7', '84.3',
       '81.9', '73.2', '94.8', '91.0', '92.2', '87.3', '82.8', '89.9',
       '74.7', '93.1', '87.8', '77.2', '85.3', '91.8', '93.8', '90.1',
       '89.1', '92.6', '94.0', '85.5%', '88.5', '87.5', '84.0', '91.1',
       '86.3', '91.4', '95.9', '95.0', '88.6', '85.4', '85.1', '71.3',
       '74.0', '96.6', '94.2', '85.9', '88.2', '93.0', '83.2', '80.5',
       '78.4', '87.9', '86.5', '77.7', '73.5', '81.6', '77.6', '61.7',
       '86.6', '79.8', '91.7', '84.2', '84.2%', '72.1', '88.1', '89.8',
       '63.9', '85.6', '95.8', '87.2', '72.0', '96.8', '82.5', '94.6',
       '95.4', '78.0', '86.2%', '89.3', '85.3%', '87.0', '89.0', '87.4',
     

# Cleaning

In [135]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

## ethylene_producer

In [142]:
copy_ethylene_producer = df['ethylene_producer'].astype(str).str.lower()
copy_ethylene_producer.unique()

array(['false', 'true', 'nan', '1', 'no', '0', 'tidak', 'ya'],
      dtype=object)

In [143]:
copy_ethylene_producer.value_counts()

,count
ethylene_producer,
false,167
true,102
nan,22
0,4
1,3
no,3
tidak,2
ya,1


In [144]:
ethylene_producer_map = {
    'false': False,
    'true': True,
    '1': True,
    '0': False,
    'tidak': False,
    'iya': True,
    'no': False,
    'nan': False
}

copy_ethylene_producer = copy_ethylene_producer.map(ethylene_producer_map)
copy_ethylene_producer.value_counts()

,count
ethylene_producer,
False,198
True,105


In [145]:
copy_ethylene_producer.fillna(False, inplace=True)
copy_ethylene_producer = copy_ethylene_producer.astype(bool)
copy_ethylene_producer.isnull().sum()

/tmp/ipykernel_3879/2527092039.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  copy_ethylene_producer.fillna(False, inplace=True)


np.int64(0)

In [146]:
df['ethylene_producer'] = copy_ethylene_producer

## freshness_score_visual

In [147]:
copy_freshness_score_visual = df['freshness_score_visual'].astype(str).str.lower()
copy_freshness_score_visual.unique()

array(['0.58', '0.82', '0.86', '0.64', '0.81', '0.69', '0.73', '0.89',
       '0.74', '0.7', 'segar', '0.65', '2.0', '0.91', '0.9', '99.0',
       '0.76', '0.87', '0.8', '0.72', '0.88', '0.61', '0.77', '0.78',
       '0.92', 'nan', '0.85', '0.71', '0.84', '0.94', '0.68', 'layu',
       '0.6', '0.93', '0.83', '0.56', '0.63', '0.66', '0.67', '0.62',
       '0.55', '-0.5', '0.57', '0.95', '0.79', '0.75', '0.96', '0.59',
       '1.5'], dtype=object)

In [148]:
copy_freshness_score_visual = pd.to_numeric(copy_freshness_score_visual, errors='coerce')
copy_freshness_score_visual.unique()

array([ 0.58,  0.82,  0.86,  0.64,  0.81,  0.69,  0.73,  0.89,  0.74,
        0.7 ,   nan,  0.65,  2.  ,  0.91,  0.9 , 99.  ,  0.76,  0.87,
        0.8 ,  0.72,  0.88,  0.61,  0.77,  0.78,  0.92,  0.85,  0.71,
        0.84,  0.94,  0.68,  0.6 ,  0.93,  0.83,  0.56,  0.63,  0.66,
        0.67,  0.62,  0.55, -0.5 ,  0.57,  0.95,  0.79,  0.75,  0.96,
        0.59,  1.5 ])

In [150]:
copy_freshness_score_visual = copy_freshness_score_visual.fillna(copy_freshness_score_visual.mean())
copy_freshness_score_visual.unique()

array([ 0.58      ,  0.82      ,  0.86      ,  0.64      ,  0.81      ,
        0.69      ,  0.73      ,  0.89      ,  0.74      ,  0.7       ,
        1.87814545,  0.65      ,  2.        ,  0.91      ,  0.9       ,
       99.        ,  0.76      ,  0.87      ,  0.8       ,  0.72      ,
        0.88      ,  0.61      ,  0.77      ,  0.78      ,  0.92      ,
        0.85      ,  0.71      ,  0.84      ,  0.94      ,  0.68      ,
        0.6       ,  0.93      ,  0.83      ,  0.56      ,  0.63      ,
        0.66      ,  0.67      ,  0.62      ,  0.55      , -0.5       ,
        0.57      ,  0.95      ,  0.79      ,  0.75      ,  0.96      ,
        0.59      ,  1.5       ])

In [152]:
df['freshness_score_visual'] = copy_freshness_score_visual

## item_type

In [159]:
copy_item_type = df['item_type']
copy_item_type.isnull().sum()

np.int64(24)

In [162]:
copy_item_type = copy_item_type.fillna('Unknown')
copy_item_type.isnull().sum()

np.int64(0)

In [207]:
df['item_type'] = copy_item_type

## respiration_rate

In [174]:
copy_respiration_rate = df['respiration_rate'].astype(str).str.lower()
copy_respiration_rate.unique()

array(['high', 'low', 'medium', 'nan', 'rendah', 'high ', 'hi', 'sedang',
       'l', 'tinggi', 'med'], dtype=object)

In [175]:
copy_respiration_rate_map = {
    'l': 'rendah',
    'hi': 'tinggi',
    'med': 'sedang',
    'high ': 'tinggi',
    'medium': 'sedang',
    'high': 'tinggi',
    'low': 'rendah'
}

copy_respiration_rate = copy_respiration_rate.map(copy_respiration_rate_map)

In [177]:
copy_respiration_rate.value_counts()

,count
respiration_rate,
rendah,130
tinggi,95
sedang,51


In [165]:
copy_respiration_rate.isnull().sum()

np.int64(19)

In [178]:
copy_respiration_rate = copy_respiration_rate.fillna('rendah')
copy_respiration_rate.isnull().sum()

np.int64(0)

In [179]:
df['respiration_rate'] = copy_respiration_rate

## sensitivity_to_chilling

In [181]:
copy_sensitivity_to_chilling = df['sensitivity_to_chilling'].astype(str).str.lower()
copy_sensitivity_to_chilling.unique()

array(['false', 'nan', 'true', '0', 'tidak', 'no', 'ya', '1', 'yes'],
      dtype=object)

In [182]:
copy_sensitivity_to_chilling_map = {
    'true': True,
    'false': False,
    '1': True,
    '0': False,
    'no': False,
    'yes': True,
    'ya': True,
    'tidak': False
}

copy_sensitivity_to_chilling = copy_sensitivity_to_chilling.map(copy_sensitivity_to_chilling_map)

In [183]:
copy_sensitivity_to_chilling.value_counts()

,count
sensitivity_to_chilling,
False,210
True,73


In [184]:
copy_sensitivity_to_chilling.isnull().sum()

np.int64(21)

In [185]:
mapping = {'High': True, 'Medium': False, 'Low': False}

copy_sensitivity_to_chilling = copy_sensitivity_to_chilling.fillna(df['respiration_rate'].map(mapping))

copy_sensitivity_to_chilling = copy_sensitivity_to_chilling.fillna(False).astype(bool)
copy_sensitivity_to_chilling.isnull().sum()

/tmp/ipykernel_3879/1151250903.py:7: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  copy_sensitivity_to_chilling = copy_sensitivity_to_chilling.fillna(False).astype(bool)


np.int64(0)

In [186]:
df['sensitivity_to_chilling'] = copy_sensitivity_to_chilling

## standard_shelf_life_fridge

In [190]:
copy_standard_shelf_life_fridge = df['standard_shelf_life_fridge']
copy_standard_shelf_life_fridge.unique()

array([  5.,  20.,   4.,   6.,  92.,   7.,  19.,  29.,  87.,  15.,  13.,
        14.,  10.,  12.,  85.,  90.,  22.,  31.,   9.,  21.,   3.,  nan,
        98.,  57.,  18., -20.,  28.,  91.,   0.,  95.,  61.,  30.,  58.,
        83.,  94.,  84.,  65.,  60.,  97.,  27.,  23.,  86.,  96.,  62.,
        81.,  88.])

In [191]:
copy_standard_shelf_life_fridge = copy_standard_shelf_life_fridge.abs()
copy_standard_shelf_life_fridge.unique()

array([ 5., 20.,  4.,  6., 92.,  7., 19., 29., 87., 15., 13., 14., 10.,
       12., 85., 90., 22., 31.,  9., 21.,  3., nan, 98., 57., 18., 28.,
       91.,  0., 95., 61., 30., 58., 83., 94., 84., 65., 60., 97., 27.,
       23., 86., 96., 62., 81., 88.])

In [192]:
copy_standard_shelf_life_fridge.isnull().sum()

np.int64(5)

In [193]:
copy_standard_shelf_life_fridge = copy_standard_shelf_life_fridge.fillna(copy_standard_shelf_life_fridge.mean())
copy_standard_shelf_life_fridge.isnull().sum()

np.int64(0)

In [203]:
df['standard_shelf_life_fridge'] = copy_standard_shelf_life_fridge

## standard_shelf_life_room

In [194]:
copy_standard_shelf_life_room = df['standard_shelf_life_room']
copy_standard_shelf_life_room.unique()

array([ 1.,  0.,  6.,  2.,  3., 44., 14., nan,  5.,  4., 26.,  7., 51.,
       12., 10., 48.,  8., 29., 27., 11., 40., 33., 32., 47., 28., 31.,
       15., 30.,  9.])

In [195]:
copy_standard_shelf_life_room.isnull().sum()

np.int64(13)

In [196]:
copy_standard_shelf_life_room = copy_standard_shelf_life_room.fillna(copy_standard_shelf_life_room.mean())
copy_standard_shelf_life_room.isnull().sum()

np.int64(0)

In [202]:
df['standard_shelf_life_room'] = copy_standard_shelf_life_room

## water_content_pct

In [197]:
copy_water_content_pct = df['water_content_pct']
copy_water_content_pct.unique()

array(['89.5', nan, '89.4', '91.2', '88.0', '82.1', '63.5', '92.8',
       '90.2', '82.7', '88.9', '79.6', '92.1', '81.1', '90.7', '63.3',
       '86.4', '85.8', '90.6', '88.4', '81.4', '87.6', '80.0', '90.8',
       '90.4', '88.3', '71.5', '89.7', '84.8', '97.0', '85.7', '82.3',
       '84.1', '87.7', '91.5', '89.6', '92.7', '61.4', '88.7', '84.3',
       '81.9', '73.2', '94.8', '91.0', '92.2', '87.3', '82.8', '89.9',
       '74.7', '93.1', '87.8', '77.2', '85.3', '91.8', '93.8', '90.1',
       '89.1', '92.6', '94.0', '85.5%', '88.5', '87.5', '84.0', '91.1',
       '86.3', '91.4', '95.9', '95.0', '88.6', '85.4', '85.1', '71.3',
       '74.0', '96.6', '94.2', '85.9', '88.2', '93.0', '83.2', '80.5',
       '78.4', '87.9', '86.5', '77.7', '73.5', '81.6', '77.6', '61.7',
       '86.6', '79.8', '91.7', '84.2', '84.2%', '72.1', '88.1', '89.8',
       '63.9', '85.6', '95.8', '87.2', '72.0', '96.8', '82.5', '94.6',
       '95.4', '78.0', '86.2%', '89.3', '85.3%', '87.0', '89.0', '87.4',
     

In [199]:
copy_water_content_pct = copy_water_content_pct.replace('%', '', regex=True)
copy_water_content_pct.unique()

array(['89.5', nan, '89.4', '91.2', '88.0', '82.1', '63.5', '92.8',
       '90.2', '82.7', '88.9', '79.6', '92.1', '81.1', '90.7', '63.3',
       '86.4', '85.8', '90.6', '88.4', '81.4', '87.6', '80.0', '90.8',
       '90.4', '88.3', '71.5', '89.7', '84.8', '97.0', '85.7', '82.3',
       '84.1', '87.7', '91.5', '89.6', '92.7', '61.4', '88.7', '84.3',
       '81.9', '73.2', '94.8', '91.0', '92.2', '87.3', '82.8', '89.9',
       '74.7', '93.1', '87.8', '77.2', '85.3', '91.8', '93.8', '90.1',
       '89.1', '92.6', '94.0', '85.5', '88.5', '87.5', '84.0', '91.1',
       '86.3', '91.4', '95.9', '95.0', '88.6', '85.4', '85.1', '71.3',
       '74.0', '96.6', '94.2', '85.9', '88.2', '93.0', '83.2', '80.5',
       '78.4', '87.9', '86.5', '77.7', '73.5', '81.6', '77.6', '61.7',
       '86.6', '79.8', '91.7', '84.2', '72.1', '88.1', '89.8', '63.9',
       '85.6', '95.8', '87.2', '72.0', '96.8', '82.5', '94.6', '95.4',
       '78.0', '86.2', '89.3', '87.0', '89.0', '87.4', '85.2', '80.8',
       '8

In [200]:
copy_water_content_pct.isnull().sum()

np.int64(26)

In [201]:
copy_water_content_pct = copy_water_content_pct.astype(float)
copy_water_content_pct = copy_water_content_pct.fillna(copy_water_content_pct.mean())
copy_water_content_pct.isnull().sum()

np.int64(0)

In [205]:
df['water_content_pct'] = copy_water_content_pct

# Pengecekan Hasil Cleaning

In [208]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 304 entries, 0 to 314
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   item_name                   304 non-null    object 
 1   item_type                   304 non-null    object 
 2   freshness_score_visual      304 non-null    float64
 3   standard_shelf_life_fridge  304 non-null    float64
 4   standard_shelf_life_room    304 non-null    float64
 5   water_content_pct           304 non-null    float64
 6   ethylene_producer           304 non-null    bool   
 7   respiration_rate            304 non-null    object 
 8   sensitivity_to_chilling     304 non-null    bool   
dtypes: bool(2), float64(4), object(3)
memory usage: 19.6+ KB


In [209]:
df.describe(include="all")

,item_name,item_type,freshness_score_visual,standard_shelf_life_fridge,standard_shelf_life_room,water_content_pct,ethylene_producer,respiration_rate,sensitivity_to_chilling
count,304,304,304.000000,304.000000,304.000000,304.000000,304,304,304
unique,43,36,NaN,NaN,NaN,NaN,2,3,2
top,Stroberi,Tropical Fruit,NaN,NaN,NaN,NaN,False,rendah,False
freq,11,68,NaN,NaN,NaN,NaN,199,158,231
mean,NaN,NaN,1.878145,18.207358,6.910653,86.362950,NaN,NaN,NaN
std,NaN,NaN,9.718378,22.076909,9.982109,6.747362,NaN,NaN,NaN
min,NaN,NaN,-0.500000,0.000000,0.000000,61.400000,NaN,NaN,NaN
25%,NaN,NaN,0.740000,6.000000,2.000000,85.100000,NaN,NaN,NaN
50%,NaN,NaN,0.840000,12.000000,4.000000,87.700000,NaN,NaN,NaN
75%,NaN,NaN,0.890000,20.000000,6.000000,90.225000,NaN,NaN,NaN


In [210]:
df.isnull().sum()

,0
item_name,0
item_type,0
freshness_score_visual,0
standard_shelf_life_fridge,0
standard_shelf_life_room,0
water_content_pct,0
ethylene_producer,0
respiration_rate,0
sensitivity_to_chilling,0


In [211]:
df.duplicated().sum()

np.int64(0)

# Extract Data

In [212]:
df.to_csv('sayur_buah_clean_v1.csv', index=False)